#指定运行环境
language: node_js

#指定nodejs版本，可以指定多个
node_js:
  - 4.4.5
  - 5

notifications:
  email:
    recipients:
      - h784124804@gmail.com
    on_success: always
    on_failure: always

services:
  - mongodb
  - redis-server

#运行的脚本命令
script:
  - gulp jslint

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master